/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author danii
 */
public class Piñon_Polanco extends javax.swing.JDialog {

    /**
     * Creates new form Piñon_Polanco
     */
    public Piñon_Polanco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        panel_norte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_sur = new javax.swing.JPanel();
        btn_limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_ingresa = new javax.swing.JButton();
        panel_centro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        txt_celular = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JLabel();
        txtF_nombre = new javax.swing.JTextField();
        txtF_apellido = new javax.swing.JTextField();
        txtF_celular = new javax.swing.JTextField();
        txtF_matricula = new javax.swing.JTextField();
        txt_semestre = new javax.swing.JLabel();
        txtF_semestre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_principal.setBackground(new java.awt.Color(204, 204, 204));
        panel_principal.setLayout(new java.awt.BorderLayout());

        panel_norte.setBackground(new java.awt.Color(204, 204, 255));
        panel_norte.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("USUARIO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_norte.add(jLabel1);

        panel_principal.add(panel_norte, java.awt.BorderLayout.NORTH);

        panel_sur.setBackground(new java.awt.Color(204, 255, 204));
        panel_sur.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_sur.setLayout(new javax.swing.BoxLayout(panel_sur, javax.swing.BoxLayout.LINE_AXIS));

        btn_limpiar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(0, 153, 255));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_limpiar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panel_sur.add(btn_limpiar);

        btn_salir.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 153, 255));
        btn_salir.setText("Salir");
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_sur.add(btn_salir);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_ingresa.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btn_ingresa.setForeground(new java.awt.Color(0, 102, 255));
        btn_ingresa.setText("Ingresar");
        jPanel1.add(btn_ingresa, java.awt.BorderLayout.PAGE_END);

        panel_sur.add(jPanel1);

        panel_principal.add(panel_sur, java.awt.BorderLayout.PAGE_END);

        panel_centro.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);

        txt_apellido.setBackground(new java.awt.Color(153, 204, 255));
        txt_apellido.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_apellido.setText("APELLIDO:");
        txt_apellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_apellido.setOpaque(true);

        txt_celular.setBackground(new java.awt.Color(153, 204, 255));
        txt_celular.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_celular.setText("CELULAR:");
        txt_celular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_celular.setOpaque(true);

        txt_matricula.setBackground(new java.awt.Color(153, 204, 255));
        txt_matricula.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_matricula.setText("MATRICULA:");
        txt_matricula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_matricula.setOpaque(true);

        txtF_nombre.setCaretColor(new java.awt.Color(102, 102, 255));
        txtF_nombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtF_nombre.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        txtF_nombre.setSelectionColor(new java.awt.Color(204, 204, 255));
        txtF_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_nombreActionPerformed(evt);
            }
        });

        txt_semestre.setBackground(new java.awt.Color(153, 204, 255));
        txt_semestre.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_semestre.setText("SEMESTRE:");
        txt_semestre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_semestre.setOpaque(true);

        javax.swing.GroupLayout panel_centroLayout = new javax.swing.GroupLayout(panel_centro);
        panel_centro.setLayout(panel_centroLayout);
        panel_centroLayout.setHorizontalGroup(
            panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_centroLayout.createSequentialGroup()
                        .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_semestre, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtF_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtF_apellido)
                            .addComponent(txtF_celular)
                            .addComponent(txtF_matricula)
                            .addComponent(txtF_semestre)))
                    .addComponent(txt_matricula)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panel_centroLayout.setVerticalGroup(
            panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido)
                    .addComponent(txtF_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_celular)
                    .addComponent(txtF_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matricula)
                    .addComponent(txtF_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_semestre))
                .addContainerGap())
        );

        panel_principal.add(panel_centro, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_principal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtF_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_nombreActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piñon_Polanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piñon_Polanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piñon_Polanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piñon_Polanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Piñon_Polanco dialog = new Piñon_Polanco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresa;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_centro;
    private javax.swing.JPanel panel_norte;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPanel panel_sur;
    private javax.swing.JTextField txtF_apellido;
    private javax.swing.JTextField txtF_celular;
    private javax.swing.JTextField txtF_matricula;
    private javax.swing.JTextField txtF_nombre;
    private javax.swing.JTextField txtF_semestre;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_celular;
    private javax.swing.JLabel txt_matricula;
    private javax.swing.JLabel txt_semestre;
    // End of variables declaration//GEN-END:variables
}
